export const mockUsers = [
  {
    username: "hse_user",
    password: "hse123",
    role: "hse",
  },
  {
    username: "kepala_user",
    password: "kepala123",
    role: "kepala",
  },
  {
    username: "direktur_user",
    password: "direktur123",
    role: "direktur",
  },
];

export const mockReports2 = [
  {
    title: "Injury Report LPR001",
    idSurat: "LPR001",
    uid: "EMP001",
    skalaCedera: 2,
    detail: "Minor finger injury caused by a metal cutting tool.",
    lokasi: "Workshop Mechanical Assembly",
    tanggal: new Date("2025-11-01"),
    status: 1,
    pesanKesalahan: "Need Validation",
    tertolak: true,
    departemen: "Mechanical Assembly",
  },
  {
    title: "Injury Report LPR001",
    idSurat: "LPR002",
    uid: "EMP002",
    skalaCedera: 3,
    detail: "Minor accident while moving electronic devices.",
    lokasi: "Electronical Assembly Area",
    tanggal: new Date("2025-11-05"),
    status: 2,
    pesanKesalahan: "",
    tertolak: false,
    headBagianApprove: new Date("2025-11-06"),
    departemen: "Electronical Assembly",
  },
  {
    title: "Injury Report LPR001",
    idSurat: "LPR003",
    uid: "EMP004",
    skalaCedera: 1,
    detail: "Slipped in the Software Installation area due to scattered cables.",
    lokasi: "Software Installation Room",
    tanggal: new Date("2025-10-28"),
    status: 3,
    pesanKesalahan: "",
    tertolak: false,
    headBagianApprove: new Date("2025-10-29"),
    direkturApprove: new Date("2025-10-30"),
    departemen: "Software Installation",
  },
  {
    title: "Injury Report LPR001",
    idSurat: "LPR004",
    uid: "EMP005",
    skalaCedera: 1,
    detail: "Fell from a ladder during warehouse inspection.",
    lokasi: "Warehouse Area",
    tanggal: new Date("2025-11-10"),
    status: 0,
    pesanKesalahan: "No section head verification yet.",
    tertolak: false,
    departemen: "Warehouse",
  },
  {
    title: "Injury Report LPR001",
    idSurat: "LPR005",
    uid: "EMP003",
    skalaCedera: 2,
    detail: "Simulation report for testing purposes, no actual incident.",
    lokasi: "Director Office",
    tanggal: new Date("2025-11-11"),
    status: 3,
    pesanKesalahan: "",
    tertolak: false,
    headBagianApprove: new Date("2025-11-11"),
    direkturApprove: new Date("2025-11-12"),
    departemen: "Direktur",
  },
  {
    title: "Injury Report LPR001",
    idSurat: "LPR006",
    uid: "EMP002",
    skalaCedera: 2,
    detail: "Low-voltage electric shock during main cable inspection.",
    lokasi: "Panel Room Electronical Assembly",
    tanggal: new Date("2025-11-03"),
    status: 2,
    pesanKesalahan: "Need validation #2",
    tertolak: true,
    headBagianApprove: new Date("2025-11-04"),
    departemen: "Electronical Assembly",
  },
  {
    title: "Injury Report LPR001",
    idSurat: "LPR007",
    uid: "EMP001",
    skalaCedera: 3,
    detail: "Leg scratched by a metal edge during machine installation.",
    lokasi: "Mechanical Assembly Section B",
    tanggal: new Date("2025-10-31"),
    status: 3,
    pesanKesalahan: "",
    tertolak: false,
    headBagianApprove: new Date("2025-11-01"),
    direkturApprove: new Date("2025-11-02"),
    departemen: "Mechanical Assembly",
  },
  {
    title: "Injury Report LPR001",
    idSurat: "LPR008",
    uid: "EMP004",
    skalaCedera: 1,
    detail: "Eye irritation due to solder smoke exposure.",
    lokasi: "Software Installation Area",
    tanggal: new Date("2025-10-29"),
    status: 1,
    pesanKesalahan: "",
    tertolak: false,
    departemen: "Software Installation",
  },
  {
    title: "Injury Report LPR001",
    idSurat: "LPR009",
    uid: "EMP005",
    skalaCedera: 2,
    detail: "Hand abrasions while lifting component boxes.",
    lokasi: "Warehouse Loading Dock",
    tanggal: new Date("2025-11-08"),
    status: 2,
    pesanKesalahan: "",
    tertolak: false,
    headBagianApprove: new Date("2025-11-09"),
    departemen: "Warehouse",
  },
  {
    title: "Injury Report LPR001",
    idSurat: "LPR010",
    uid: "EMP003",
    skalaCedera: 3,
    detail: "Simulation report for annual audit without actual injury.",
    lokasi: "Director Meeting Room",
    tanggal: new Date("2025-11-02"),
    status: 0,
    pesanKesalahan: "",
    tertolak: false,
    headBagianApprove: new Date("2025-11-02"),
    direkturApprove: new Date("2025-11-03"),
    departemen: "Direktur",
  },
  {
    title: "Injury Report LPR001",
    idSurat: "LPR011",
    uid: "EMP001",
    skalaCedera: 1,
    detail: "Shoulder injury while lifting heavy components.",
    lokasi: "Mechanical Assembly Zone A",
    tanggal: new Date("2025-11-04"),
    status: 2,
    pesanKesalahan: "",
    tertolak: false,
    headBagianApprove: new Date("2025-11-05"),
    departemen: "Mechanical Assembly",
  },
  {
    title: "Injury Report LPR001",
    idSurat: "LPR012",
    uid: "EMP004",
    skalaCedera: 3,
    detail: "Entangled in long cables within the work area.",
    lokasi: "Software Installation Hall",
    tanggal: new Date("2025-10-27"),
    status: 3,
    pesanKesalahan: "",
    tertolak: false,
    headBagianApprove: new Date("2025-10-28"),
    direkturApprove: new Date("2025-10-29"),
    departemen: "Software Installation",
  },
  {
    title: "Injury Report LPR001",
    idSurat: "LPR013",
    uid: "EMP002",
    skalaCedera: 1,
    detail: "Head bumped against workbench during tool testing.",
    lokasi: "Lab Electronical Assembly",
    tanggal: new Date("2025-11-06"),
    status: 0,
    pesanKesalahan: "",
    tertolak: false,
    departemen: "Electronical Assembly",
  },
  {
    title: "Injury Report LPR001",
    idSurat: "LPR014",
    uid: "EMP005",
    skalaCedera: 2,
    detail: "Foot tripped over equipment in warehouse area.",
    lokasi: "Warehouse Section C",
    tanggal: new Date("2025-11-07"),
    status: 1,
    pesanKesalahan: "",
    tertolak: false,
    departemen: "Warehouse",
  },
  {
    title: "Injury Report LPR001",
    idSurat: "LPR015",
    uid: "EMP003",
    skalaCedera: 2,
    detail: "System inspection report by the director.",
    lokasi: "Main Office",
    tanggal: new Date("2025-11-09"),
    status: 3,
    pesanKesalahan: "",
    tertolak: false,
    headBagianApprove: new Date("2025-11-09"),
    direkturApprove: new Date("2025-11-10"),
    departemen: "Direktur",
  },
];
